// +build ignore

package main

import (
	"io/ioutil"
	"log"
	"os"
	"os/exec"
	"strings"

	"github.com/gopherjs/gopherjs/compiler/prelude"
)

func main() {
	cmd := exec.Command("uglifyjs")
	cmd.Stdin = strings.NewReader(prelude.Prelude)

	out, err := cmd.CombinedOutput()
	if err != nil {
		log.Fatalf("uglifyjs: %v\n%s", err, out)
		os.Exit(1)
	}

	err = ioutil.WriteFile("prelude_min.go", []byte(`// Code generated by regen. DO NOT EDIT.

package prelude

const Minified = `+"`"+string(out)+"`\n"), 0644)

	if err != nil {
		log.Fatal(err)
	}
}
